services:
  playground-csharp:
    container_name: 'playground-csharp'
    hostname: 'csharp'
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    working_dir: '/workspace'
    tty: true
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace
